vim.g.mapleader = " "
vim.g.maplocalleader = " "

vim.o.shiftwidth = 4
vim.o.tabstop = 4
vim.o.expandtab = true
vim.o.number = true
vim.o.relativenumber = true
vim.o.termguicolors = true
vim.wo.signcolumn = 'yes'
vim.o.ignorecase = true
vim.o.smartcase = true
vim.o.updatetime = 250
vim.o.timeout = true
vim.o.timeoutlen = 300
vim.o.pumblend = 30 -- Popup blend
vim.o.pumheight = 15 -- Maximum number of entries in a popup
vim.o.scrolloff = 4 -- Lines of context
vim.o.undofile = true
vim.o.undolevels = 10000
vim.o.updatetime = 200 -- Save swap file and trigger CursorHold
vim.o.wildmode = "longest:full,full" -- Command-line completion mode
vim.o.winminwidth = 5 -- Minimum window width
vim.o.wrap = true -- Disable line wrap
vim.o.splitkeep = "screen"
